# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ywzyxsocool"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "BiliBili"
url = "https://space.bilibili.com/558633941"

[social.params]
icon = "brand-bilibili"
