# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
favicon = "img/favicon.png"
rssFullContent = true

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy = "default"

[footer]
customText = ""
since = 2020

[dateFormat]
lastUpdated = ":date_full"
published = ":date_full"

[sidebar]
avatar = "img/avatar.png"
subtitle = "这里是 PassionMortal 放细碎的地方。"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
default = "Licensed under CC BY-NC-SA 4.0"
enabled = true

[widgets]
homepage = [
  {type = "search"},
  {type = "archives", params = {limit = 5}},
  {type = "categories", params = {limit = 10}},
  {type = "tag-cloud", params = {limit = 10}},
]
page = [{type = "toc"}]

[opengraph.twitter]
card = "summary_large_image"
site = ""

[colorScheme]
default = "auto"
toggle = true

## Comments
[comments]
enabled = true
provider = "disqus"

# See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
# Copy the configurations you need from there and paste it here.
